// API REST de Usuários
@baseURL = http://localhost:3000/user
@id = 2
###
// GET 
GET {{baseURL}}
Content-Type: application/json

###
// GET - By id
GET {{baseURL}}/{{id}}
Content-Type: application/json

###
//POST
POST {{baseURL}}
Content-Type: application/json

{
    "id": 2,
    "nome": "UserTest",
    "telefone": "",
    "email": "usertest1email@gmail.com",
    "senha": "user1password1234",
    "cpf": "123.456.789-01",
    "cep": "121345-678",
    "cidade": "USer1 City TestCityName",
    "bairro": "User1 Neigborhood TestNeigborhoodName",
    "rua": "User1 Rua TestRuaName",
    "numero": 123,
    "complemento": null,
}

###
//PUT
PUT {{baseURL}}/{{id}}
Content-Type: application/json

{
    "id": 2,
    "nome": "UserTest2",
    "telefone": "(12) 34567-8901",
    "email": "usertest1email@gmail.com",
    "senha": "user1password1234",
    "cpf": "123.456.789-01",
    "cep": "121345-678",
    "cidade": "USer1 City TestCityName",
    "bairro": "User1 Neigborhood TestNeigborhoodName",
    "rua": "User1 Rua TestRuaName",
    "numero": 123,
    "complemento": null,
}

###
//DELETE
DELETE {{baseURL}}/{{id}}
Content-Type: application/json
